### ISSUE TITLE
Split Vertices on Polygon

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#105]
While editing the polygons I have run into the following problem a few times. Sometimes while moving a vertex to a new location it will split into two vertices (one stays behind in the original spot). Afterwards, I am unable to move either vertex around, and the only way to solve this issue is to delete the entire polygon and start again. 

![image](https://user-images.githubusercontent.com/12621062/186036255-99464345-0e92-491d-8012-debff28b40ae.png)

**Comment by bruce-wayne99** [comment]
I think there is another issue tracking the same bug. Closing this one.
