### ISSUE TITLE
Error Saving new Neuroglancer "view"

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#11]
I went to https://webdev.dk.ucsd.edu/activebrainatlas/admin and logged in to Django portal (to authenticate w/ webserver and create session variable)

I loaded Neuroglancer on webdev.dk.ucsd.edu in separate browser tab (used 'Preview' button)

I created new image layer and closed 'C1' (default loaded on previous click).  In new image source I pasted:
precomputed://https://activebrainatlas.ucsd.edu/data/MD589/neuroglancer_data/C1

I then renamed 'view' to MD589 (see screenshot below)

![image](https://user-images.githubusercontent.com/25622382/159366554-50d9538d-38f6-48c4-a123-265e847826f1.png)

Finally I tried to save with 'Save' but received Internal Error message - see debug message

**Comment by eddyod** [comment]
This was fixed with the owner/owner_id problem. Please try again and either close this issue or report the bug still exists.
