### ISSUE TITLE
Ability to change size of contour vertices and shade of contour edges

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#12]
Follow the tool that Ed created for marking cells.

**Comment by madwilliam** [comment]
to get to the rendering tool. click on an annotation layer, then click on the rendering tab

**Comment by eddyod** [comment]
There is existing code in the neuroglancer project:
src/neuroglancer/annotation/annotation_layer_state.ts:88

/* START OF CHANGE: Point Annotation Marker Size */
const DEFAULT_FRAGMENT_MAIN = `
#uicontrol float size slider(min=0, max=10, default=1)
void main() {
  setColor(prop_color());
  setPointMarkerSize(size);
}
`;
/* END OF CHANGE: Point Annotation Marker Size */

**Comment by bruce-wayne99** [comment]
Working version live at webdev.
Steps:
- Go to webdev.dk.ucsd.edu, click on access preview.
- Draw some polygons
- Go to "Rendering" tab to adjust polygon related properties.
