### ISSUE TITLE
polygon volume definitions to add

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#120]
IRT_L
IRT_R
5PR_L
5PR_R
5MOT_L
5MOT_R

For subregions-is it sufficient to request a new volume name for a polygon to be drawn within an existing volume
Is it possible for cell detector to use polygon/volumes as a ROI

**Comment by drinehart1** [comment]
We will still need descriptions prior to adding to database

**Comment by bruce-wayne99** [comment]
Discussed in dev meeting.
