### ISSUE TITLE
Polygon and alignment to active atlas

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#122]
Ideal is for display of multiple volumes along with cell annotations associated with those volumes each aligned to active atlas
without images
(Ed +Naga+ Duane+William+Kui)

in order to do this we would need the cell detector to work within a selected volume as the ROI

**Comment by drinehart1** [comment]
close bug once Marissa signs off

**Comment by befriedman** [comment]
Hi Duane,

Your email to me is not clear.

please indicate who should close the bug. I am not sure that I should since I did not fix the bug.

Thanks,

Beth
________________________________

**Comment by drinehart1** [comment]
This was a comment added today at Neuroglancer collab meeting.  

 

For this bug, Naga will make modifications, Marissa will test (Naga will let her know) and then bug will be closed (but either Naga or Marissa).  

 

David was focused on cleaning up the bug list today so we updated ~10.  You may have additional e-mails that are automatically generated by github.

 

Duane
