### ISSUE TITLE
Pulldown for volume selection

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#123]
can a search box be added so that one can type in to navigate to a landmark  for selection rather than scroll through a growing list of landmarks

**Comment by bruce-wayne99** [comment]
Requires using select2 inbuilt library but its not currently compatible with typescript. Only react version is present. Alternate is to search by typing after opening the dropdown. Will re-open the issue if the alternative is not usable.
