### ISSUE TITLE
Adding auto-save to browser

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#125]
Is it possible to have auto-save active on the browser only to save annotations? Want to prevent losing work on a working polygon if website crashes suddenly

**Comment by bruce-wayne99** [comment]
Add "not saved"/"saved" on the annotation tabs page.

**Comment by bruce-wayne99** [comment]
Toggle "not saved" with no text

**Comment by drinehart1** [comment]
Marissa needs to test

**Comment by bruce-wayne99** [comment]
Only annotations change: Show "not saved"

**Comment by bruce-wayne99** [comment]
Change has been added to webdev: https://webdev.dk.ucsd.edu/preview/?id=393
