### ISSUE TITLE
Inconsistent annotations across tables

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#126]
DK61: https://activebrainatlas.ucsd.edu/ng/?id=710
Only unaided premotors are annotated
1. "annotation sessions" include a "null category" - I don't know what the Null category is logging because I never selected this
2. Points table  indicates that the number of premotor cells is 418
3. Marked cells tables indicates that 418 cells total but there is also a number "356" 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/59492402/194373583-b832ee52-a55c-497b-8958-4ac7148cddcc.png">

**Comment by eddyod** [comment]
The NULL category is applied when there is no cell type to the marked cell. Maybe we need to make the cell type required? Setting it to NULL, which is actually a string is confusing.

**Comment by befriedman** [comment]
Not sure how to reply- since I did not select null- I have no idea which cells were categorized as nulls- or why some were parsed correctly as positives and some were not

Maybe if we could identify specific cells that were id'ed as nulls we could see if there was something in url that was different in the way they were QC'ed?
________________________________

**Comment by befriedman** [comment]
yeh- got me by the sneakers- did not know that one could even do this

...sounds like Beth-the- natural-bug-detector at work...
________________________________

**Comment by madwilliam** [comment]
Null right now stand for unQCed or unmarked.  We can make that an explicit category by changing the column definition in the database.

**Comment by madwilliam** [comment]
Ed, does your pivot table exclude null for the display?

**Comment by eddyod** [comment]
That's the problem. It includes them in the Total on the bottom, but not in the rows. In the rows, it is doing an inner join so it is not catching NULL values.

**Comment by eddyod** [comment]
I want to update the NULL values to UNQC, and add that to the database column definition and force the field to be required.
And why is cell type referred to as Category in Neuroglancer?

**Comment by eddyod** [comment]
Here is  a screenshot of what I want to modify. I want to change the name 'Category' to 'Cell type' as the data comes from the cell type table. I also want to make this field required.
![cell_type screenshot](https://user-images.githubusercontent.com/7785741/204289498-3f4be725-37ad-4d62-87fc-3a65bbf072ce.png)

**Comment by befriedman** [comment]
Ok- so appears when no machine detector had ever been run but also in QC runs- Marissa notes that in DK62 and DK50 (post-QC) one cell was marked "null". Again no changes were made in the course of QC or annotation by either of us. Julian =1 null DK41 - inter-rater case. Julian - DK62 and DK50 no nulls. I am confused by the sporadic nature of this. Maybe need to try Ed's fix on a new case where the annotations are not done in advance of QC as this had the most frequent occurrence. ALso note that this seems to be a new defect as the original training sets (all manual annotations) do not have these null cases cropping up when we first manually marked cells.- Is there a way to track back to the original code to see what changed?

**Comment by befriedman** [comment]
Originals without any nulls from way back when:
DK55-id=347

**Comment by befriedman** [comment]
other issue with data table
It would be good to be able to retrieve id number of neuroglancer case (in addition to DK number) so that the data in data table could be traced back to the specific neuroglancer state

Also the "date created" in the annotation session table is not logging correctly since there are dates creates by Hannah 
that are after she already left the lab...???

**Comment by madwilliam** [comment]
> other issue with data table It would be good to be able to retrieve id number of neuroglancer case (in addition to DK number) so that the data in data table could be traced back to the specific neuroglancer state
> 
> Also the "date created" in the annotation session table is not logging correctly since there are dates creates by Hannah that are after she already left the lab...???

The date added table reflect the date when we moved hannah's annotation to the new schema yoav created

**Comment by befriedman** [comment]
Thanks Ed! This sounds great- but I must be doing something wrong as I don't see these implementations when I navigate to portal (annotation sessions table) vis webdev.

?
________________________________

**Comment by eddyod** [comment]
The improvements will be mostly hidden from the user. 
1 .There won't be any redundant data saved. 
2. The archives can be viewed and restored: https://webdev.dk.ucsd.edu/activebrainatlas/admin/neuroglancer/archiveset/
3. The number of sessions has been greatly reduced and is easier to track with the number of points in a session on this page: https://webdev.dk.ucsd.edu/activebrainatlas/admin/neuroglancer/annotationsession/

**Comment by befriedman** [comment]
Hi Ed,

Ok- some miscommunication- it would be useful to have actual session number attached to the table- so that we can determine which of the sessions for a given brain contains the source annotations. Is this possible?

Marissa and I are going through the neuroglancer state table- opening individual sessions and summarizing what data is in that particular session

William created several sessions that have images of one brain with atlas alignments of annotations from another brain- nearly impossible for anyone from the outside to make sense of this

I have asked her to share her google sheet with you and me so you can see what we are tracking.

If it turns out that it is pretty straightforward to move annotation sets around then perhaps some of these neuroglancer states can be deleted?

Thoughts?

Beth
________________________________

**Comment by eddyod** [comment]
On the current https://activebrainatlas.ucsd.edu production server, a new session is created EVERY time a user clicks the 'Save Annotations' button in Neuroglancer. I removed this, and now a session will only be created/saved per neuroglancer view/Annotator/cell type.
This will cut down drastically on the number of sessions and it will be easier to correlate a view with a session. In the session table, I will add the link to the Neuroglancer view.

And remember, when creating a new marked cell editing session, you must select the cell type (Category). I don't know if Naga ever made this field required or not.

**Comment by befriedman** [comment]
this is good for going forward
but to track back and understand what we have- it would be hugely useful to have the session id popup somewhere on the annotation table

Is this impossible to add-
________________________________

**Comment by eddyod** [comment]
Beth, you're right. All the new data will be easy to track, but the existing data is a mess. I'll see if I can edit the existing data to include the Neuroglancer ID in the session.

**Comment by befriedman** [comment]
Do you want to wait for Marissa and I to finish the QC on Neuroglancer State Table

I have a feeling that we will end up deleting many sessions (with data) since I am seeing that some of this stuff is Williams alignment of manual annotations from one brain onto images of another brain

If we have a good protocol of annotation alignment, I am not sure that we really need to store the outcomes of alignments since we should be able to generate these on the spot.

Furthermore, I am not sure that we are even going to want to stick with the current program of aligning to the Active Atlas- If the Allen Institute becomes interested then I bet we will switch to alignments to the Allen Atlas- (we will still need a routine for doing this but the reference space will change)

So many discussions... so little time

and... have no idea where you are but hope you are having fun!

Best,
Beth
________________________________

**Comment by drinehart1** [comment]
Added 'Unknown' as option in dropdowns, and if user picks nothing, landmark will default to unknown.  This is on Neuroglancer front-end but tested save/retrieve functionality

**Comment by eddyod** [comment]
I updated the database and put the new neuroglancer on the production server. There will no longer be any NULL cell type annotations.
