### ISSUE TITLE
Draw Mode for CELLS fails after using View Mode for a while

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#127]
When using Draw Mode for CELLS, sometimes switching Draw Mode fails to create a mark after switching from View Mode (this happens without ending the cell annotation session). Not sure how long user has to be on View Mode before the Draw Mode fails. It has not failed when constantly switching from one to the other.

**Comment by bruce-wayne99** [comment]
Issue has been fixed.
