### ISSUE TITLE
Adding a vertex in edit mode breaks other vertices apart

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#130]
I am testing the volume tool by drawing a sub-region polygon within a main region polygon. One issue that appears on both polygons is that if the user is in "edit mode" and decides to add a vertex point, then moving any surrounding vertex points next to the added one will separate the vertices. All separated vertices can be moved around, and the annotations can even be saved even though the polygon is not closed. I also tested the propagation tool and it copies the disconnected polygon to the next section. 

<img width="1440" alt="Screen Shot 2022-11-01 at 1 43 58 PM" src="https://user-images.githubusercontent.com/12621062/199351479-72b0f5f4-6ed5-40cd-94f6-6bbfd8596290.PNG">
<img width="1440" alt="Screen Shot 2022-11-01 at 1 53 42 PM" src="https://user-images.githubusercontent.com/12621062/199351492-77593829-1793-4a9e-bb68-b263713e0052.PNG">
<img width="1440" alt="Screen Shot 2022-11-01 at 1 54 49 PM" src="https://user-images.githubusercontent.com/12621062/199351496-58ed9118-0f48-4c6c-bedf-8325c1cafc84.PNG">

Additionally, you can delete a vertex point that is in between two other vertices, but any edge vertices cannot be deleted. 
<img width="1440" alt="Screen Shot 2022-11-01 at 1 56 15 PM" src="https://user-images.githubusercontent.com/12621062/199351542-96695919-d256-4502-996a-55e54334b643.PNG">

**Comment by bruce-wayne99** [comment]
Duplicate issue: https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/issues/105

keeping this open.

**Comment by bruce-wayne99** [comment]
This has been fixed. @mm6654 this requires redrawing the polygons in which the bug took place.

**Comment by bruce-wayne99** [comment]
`Ui/annotations.ts` contains the code for fixing this.

**Comment by bruce-wayne99** [comment]
Issue occurs when all the points are not in the same plane. For example the current vertices in the polygon are in section: 234.50001 but the newly created point is at location 234.5 hence the issue.

**Comment by bruce-wayne99** [comment]
This issue has been fixed. Reproduced at link: https://webdev.dk.ucsd.edu/preview/?id=393

Now the vertices don't break.
