### ISSUE TITLE
Missing documentation for feature on Neuroglancer

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#134]
There are a few options on the Neuroglancer page that does not have any documentation. What are the "segments" and the "Ignore null related segment filter" options used for?

![image](https://user-images.githubusercontent.com/12621062/199593431-32b133a5-ccb2-4f25-8d36-20cbb3153ee0.png)

**Comment by drinehart1** [comment]
I have no idea

**Comment by madwilliam** [comment]
Ed and I don't know what it's for either.

**Comment by drinehart1** [comment]
Naga - we can remove this "feature" in upcoming release

**Comment by bruce-wayne99** [comment]
Issue has been resolved. Changes will appear in latest deployment.
