### ISSUE TITLE
Can create multiple polygons of the same volume on single layer 

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#139]
I tested out the propagation tool, and when I tried drawing another polygon on the same section it let me create it. I still got the error message, but the polygon was still visible. Again, these are polygons of the same volume in a single section - but this only happens if I propagate the polygon from one section to the next. Below are two different volumes, each with multiple polygons in the same section. In the first picture the error message appeared after drawing two polygons.

![image](https://user-images.githubusercontent.com/12621062/203180597-844fd806-58b2-428f-bd56-2ac6d90278e4.png)
![image](https://user-images.githubusercontent.com/12621062/203181075-3d8e3594-4072-4831-918f-5c914d1716cc.png)

**Comment by mm6654** [comment]
This was done on the WebDev preview

**Comment by bruce-wayne99** [comment]
Discussed with Marissa. Bug was not reproducible. The issue will be opened again if the bug appears again.
