### ISSUE TITLE
scan run table

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#144]
there are some wacko scan runs listed- e.g. "X"
since there is no tab to id the origin of this data we can't make sense of it
can you add a field so that initials of person that inputs data are added?

**Comment by eddyod** [comment]
I added that X brain. That was short for Xiang's data, I didn't know what else to call it. 

I can add the username to the scan run table.

**Comment by befriedman** [comment]
makes sense-

is it a neuroglancer state though- since it is the portal?

Thanks,

Beth
________________________________
