### ISSUE TITLE
brainsharer

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#145]
All Brainsharer- instead of premotor , starter tags for channels - Please change to Neurotrace, Red channel, Green Channel
DK55- z is set at 10 um: should be 20 um
DK52- slice 183- neurotrace like staining is present in red channel
DK46- z is set at 10 um: should be 20 um

**Comment by drinehart1** [comment]
Permission adjusted so Marissa can login (thanks, Ed)
