### ISSUE TITLE
"Save annotations" button is not working 

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#146]
Button does not work on WebDev and sometimes fails on Active Brain Atlas. Displays the following error message: 

This is on WebDev:
<img width="1280" alt="Screen Shot 2022-11-30 at 1 19 50 PM" src="https://user-images.githubusercontent.com/12621062/204910364-7f0ec474-7463-4be6-98c6-534b355a0828.png">

**Comment by drinehart1** [comment]
I believe this is related to unavailability of webdev server.  I believe this problem will be solved [to some extent] if we split API calls and images.  As callbacks for annotation storage are critical, we can test by loading images from imageserv but maintaining annotations on webdev/aba.

**Comment by mm6654** [comment]
I have been testing this for a couple days and so far the annotations button is functional.

**Comment by drinehart1** [comment]
confirmed
