### ISSUE TITLE
volume session

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#16]
ability to “start/stop” session of editing/creating polygons (and make more obvious user is in specific mode)

ref: https://docs.google.com/document/d/1EOX_WuVZP5M6tXFWuI4yugBwIK_FyXaIspZHmYeRKxo/edit?usp=sharing

**Comment by bruce-wayne99** [comment]
Working version live at webdev.
Steps:
- Go to webdev.dk.ucsd.edu, click on access preview.
- Create a new annotation layer
- Click on the volume tool button present in the top right corner of the annotations tab to start using volume session.
