### ISSUE TITLE
Can create cell types without defining them in portal first

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#167]
This issue is related to issue #166 from last week. Yoav had mentioned that he wanted a drop down option for selecting cell types in order to avoid the option of being able to type in a new cell type in the NG viewer. In order to add cell types to the NG viewer drop-down, Yoav specified that cell types should be added only through the portal prior to starting a cell annotation. Having the drop-down option ensures all cell types are registered with the database.

Issue #166 had an unregistered cell type and prevented users from finding their information through the portal. Now the question is how was a link generated with an unregistered cell type?

**Comment by eddyod** [comment]
We did look into this and you must have a cell type to enter a marked cell.

**Comment by eddyod** [comment]
This has been replaced with labels.
