### ISSUE TITLE
Nginx config problem with newly created structures

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#170]
Once a new segmentation is created via Neuroglancer, the provided URL results in an error.

https://www.brainsharer.org/structures/DK61_4N_R/

**Comment by drinehart1** [comment]
I don't understand where the underlying data is stored.  Once the data is created, we should store it on imageserv.  I expected somewhere like /data/{brain_id}/{structure} and the create symbolic link from there to /data/neuroglancer/{brain_id}/{structure}.  If this format/schema is used, the structures will be accessible @ https://imageserv.dk.ucsd.edu/data/{brain_id}/{structure}.  This link is what we should store in db for structure layer.

**Comment by drinehart1** [comment]
I copied folders to imageserv for now.  These meshes are available there. example: https://imageserv.dk.ucsd.edu/data/structures/DK79_TG_L/

 

I’m a little unclear how to test as this should work ‘as is’ given the regular expressions in nginx config for precomputed image stacks.
