### ISSUE TITLE
Gmail login needs a special link to access brainsharer admin

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#171]
Add gmail capability to the brainsharer admin login.

**Comment by drinehart1** [comment]
Do you have an example link where gmail is trying to verify/validate?  We can create alias to specific path/file as needed.

**Comment by eddyod** [comment]
Go to  https://www.brainsharer.org, then the login page and use the Google login link. This will successfully allow you to login to the public website but if you then go to the https://www.brainsharer.org/brainsharer/neuroglancer/ admin portal, you must login in again. I'm not sure if you can access the portal with just the Google login. You might need a local user and password. I'll look into this more.

**Comment by eddyod** [comment]
I fixed this. Please test. 
1. Go to https://www.brainsharer.org/brainsharer/admin and make sure you are NOT logged in, if logged in, logout in the link in the upper right.
2. Go to https://www.brainsharer.org and make sure you are not logged in. Again. logout if needed. Then go to the login page and use the Google login link. This should log you in and redirect you back to https://www.brainsharer.org. 
3. Look for the menu under your username in the top right, go to the admin page, you should be able to see the admin pages.

**Comment by drinehart1** [comment]
1.	Login (non-gmail) works
2.	Login w/ gmail works
3.	‘admin’ page link works

 

Duane

**Comment by Yusup-Badiev** [comment]
Just tested this an it works, I think the issue can be closed
