### ISSUE TITLE
Check users in Neuroglancer states

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#173]
Are all the users correct in the Neuroglancer state listings?

**Comment by drinehart1** [comment]
Is this for brainsharer.org or for activebrainatlas.ucsd.edu?  I believe the databases are separate at this point, right?

**Comment by eddyod** [comment]
Yes the databases are separate. I'm wondering if the sql I used to load users is correct. Gal Mishne seems to own a bunch of Neuroglancer states. Please check the ETL script under the brainsharer branch:
https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/blob/brainsharer/sql/brainsharer.ETL.sql

**Comment by drinehart1** [comment]
You may have error in the following query:

 


INSERT INTO brainsharer.annotation_session (id, annotation_type, FK_user_id, FK_prep_id, FK_state_id,

	
FK_brain_region_id, active, created, updated)

	
SELECT id, annotation_type, FK_annotator_id, FK_prep_id, FK_state_id,

	
FK_structure_id, active, created, updated

	
FROM active_atlas_development.annotation_session

	
WHERE FK_annotator_id IN (2,3,41,23,16,38,40)

	
ORDER BY id;

 

 

From what I can ascertain, if the annotator was originally set (and is one of : 2,3,41,23,16,38,40), this will populate annotation_session table.  Gal is user 41 but I don’t think she originally created any annotations unless to demonstrate that it is possible.  The more likely scenario is that either Marissa or I was logged into the system while testing/demonstrating annotation creation (or copying an existing one).  I sent e-mail to Gal to confirm – just to be on safe side.

Duane

**Comment by drinehart1** [comment]
just verified with Gal -she has not been on site and has not created URL states.  Those may be deleted

**Comment by eddyod** [comment]
I was inserting the users incorrectly. I fixed it.
