### ISSUE TITLE
Add password reset on brainsharer

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#176]

**Comment by eddyod** [comment]
Which SMTP server can we use for the password reset process? It needs to send out an email.

**Comment by drinehart1** [comment]
Use the active brain sharer account on gmailSent from my iPhoneOn Apr 19, 2023, at 20:19, eddyod ***@***.***> wrote:﻿
Which SMTP server can we use for the password reset process? It needs to send out an email.

**Comment by eddyod** [comment]
Never mind,
smtp.ucsd.edu

**Comment by eddyod** [comment]
I added the local signup, password reset, login forms and they are hopefully all working but need testing.

https://brainsharer.org

**Comment by eddyod** [comment]
Done.
