### ISSUE TITLE
Error saving annotations

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#190]
Beth had trouble saving annotations and received an error. The error was due to there being no FK_brain_region_id sent in the REST PUT. This is the 'description' field that Yusup has been working on. I made that field required in the Neuroglancer code but it was not deployed. I made a change in the Django code to fill in a default in case it was empty, but that field should also be required in the Neuroglancer code.

**Comment by mm6654** [comment]
We are having trouble saving annotations again. Neither of the buttons are working, and both give the same "Internal error: please see debug message"

**Comment by eddyod** [comment]
I realized another problem with the 'Saving annotations' process. Currently the save process will insert new points, but if a user moves or deletes existing points, those will not be touched. They will remain in the database. I see two options:
1. When the user clicks the 'Save Annotations' button, that existing data is deleted then reinserted.
2. We get rid of the 'Save Annotations' button and just parse the point data from the existing saved JSON data. 

I think the 2nd option is better as the data is already there and being correctly saved. But now we need to parse the data out to fill the dropdowns for the Import functionality.

**Comment by eddyod** [comment]
For now, I am going to implement the 1st option. I just tested in on my local machine and it works well and it is quick and robust. We can implement the 2nd one later.

**Comment by eddyod** [comment]
Saving annotations has been completely redone.
