### ISSUE TITLE
Issue Importing Polygons from link id=668 to link id=758 in Brainsharer

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#191]
I originally created polygons for DK73 in link id = 668, and when I tried to import those poygons into a new link for DK73 id = 758 I ran into the following problem:

First image is the imported DK73 polygon into link id=758. It is in section z=167, and it looks like this:
![image(3)](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/da9232f2-4034-44e1-b95b-d9802e83cc06)

Second image is the original polygon drawn for DK73 link id=668. It is in section z=167 and it does not look like the imported version.
![image(4)](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/ecf3fc9e-fcac-4add-bbed-e003dd9e7df8)

--

Another imported polygon for DK73 in link id=758 located on section z=165 looks like this:
![image(5)](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/68f3a9a9-ae43-4fec-b848-e49e4085eaa2)
 
The original polygon drawn in DK73 link id=668 located on the same section z=165 looks normal:
![image(6)](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/91883a61-8de6-4f6b-9b14-26cd7030982a)

--

The importing issue only happened to a few polygons. The other polygons that were imported looked normal as shown below:

Imported polygon into link id=758 located on section z=116 looks normal:
![image(7)](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/e2db6b2b-be75-45ae-bfcf-714a018376b9)

Original polygon on link id=668 looks the same on section z=116:
![image(8)](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/77e40727-86a7-455e-934c-65765519711d)

**Comment by eddyod** [comment]
The data is being imported correctly, it was an error with saving it.

**Comment by eddyod** [comment]
This has been fixed and deployed. Please test and close this issue.

**Comment by mm6654** [comment]
Tested and import was okay from one link to another
