### ISSUE TITLE
nginx issue on imageserver

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#192]
When requesting this url:
https://imageserv.dk.ucsd.edu/data/X/neuroglancer_data/mesh/names/info

I get a 404 error even though I am sure file exists. Looking at the error log it is trying to find:
open() "/data/neuroglancer/neuroglancer_data/mesh/names/info" failed (2: No such file or directory)
I assume this is some nginx config error.

**Comment by eddyod** [comment]
Accessing the info files from nginx is problematic. When you access an info file from activebrainatlas, it displays in the browser as it should:
https://activebrainatlas.ucsd.edu/data/X/www/neuroglancer_data/mesh/names/info
Accessing the same file from imageserv results in a 404 error, so it must be an nginx config problem.
https://imageserv.dk.ucsd.edu/data/X/neuroglancer_data/mesh/names/info

**Comment by drinehart1** [comment]
I believe error is from the regular expressions configured in Nginx.  The current pattern matching works for some brains but not others.  That is problematic in that I can't configure a standard regular expression to match all brains if the file structure for brains is not standardized.

For example:
DK55: DK55/www/neuroglancer_data/CH1_allen25um (used on brainsharer)
DK55: DK55/neuroglancer_data/CH[1-3] (unclear where used)

DK52 (similar to DK55 above)

+++
Until we finalize a better way to store imaging data with better security (which may be swapped out for Minio/S3 at some point), I'm switching back to apache on imageserv.dk.ucsd.edu.  Preliminary testing seems to work but please verify before closing.

**Comment by eddyod** [comment]
I can easily change 'X' to 'DKX1'. But then we have brains called DK122, MD589. Maybe a regex that starts with D or M and ends with a number? But Apache is fine if it there is no performance difference.

**Comment by drinehart1** [comment]
No need to change at present due to apache fix.

**Comment by eddyod** [comment]
I tested a segmentation with:
https://imageserv.dk.ucsd.edu/data/X/www/neuroglancer_data/mesh_2_singleres
and it loads fine.

**Comment by drinehart1** [comment]
Very good news - thanks
