### ISSUE TITLE
X Ji url id = 250

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#193]
error message on attempt to open id=250 (10 um layer)
  fetch error HTTP error 0: Network or CORS error

**Comment by eddyod** [comment]
The URLs were reflecting the old data layout. They have been updated and fixed and it loads now.

**Comment by befriedman** [comment]
thank you!

Is it possible to shift to a 3 or 5 um resolution stack?
________________________________

**Comment by eddyod** [comment]
There is a 3um layer.

**Comment by befriedman** [comment]
oops
thank YOU

not ypu
________________________________
