### ISSUE TITLE
 Neuroglancer states not saving changes to view/render settings

### ISSUE THREAD

**Issue by SanjeevRJ** [ActiveBrainAtlas2/activebrainatlasadmin#203]
When a neuroglancer state is opened from BrainSharer and edits are made to the view/render settings, they do not persist when the state is closed and reopened.

**Comment by eddyod** [comment]
I redid the login process. This was preventing users from being able to save properly. Try logging out, relogin and make sure the URL is not read only.

**Comment by SanjeevRJ** [comment]
How do I change a url to not read only?

**Comment by eddyod** [comment]
Go to: https://www.brainsharer.org/brainsharer/admin/neuroglancer/neuroglancerstate/
Search for the data you want to change/view.
Click the link near the left column under 'ID' 
An edit page appears, toggle the read-only checkbox, it it is checked, then saving is not possible. Uncheck to save in Neuroglancer. You can also filter the searches by 'Read-only' in the search page filter on the right side of the page.

**Comment by mm6654** [comment]
I tested this, and it seems to be working fine now.
