### ISSUE TITLE
remove 'save annotations' button in ng (when user not logged in)

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#205]
![image](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/25622382/7edae7d0-e265-488b-a583-51035282ff3c)

We should remove the 'save annotations' button (see screenshot) when user is not logged in (to avoid getting hopes up that annotations may be saved).

**Comment by eddyod** [comment]
Good idea.

**Comment by eddyod** [comment]
I added this to https://www.brainsharer.org/ng_demo and https://demo.brainsharer.org/ng
Please test and close.

**Comment by drinehart1** [comment]
works like a charm!
