### ISSUE TITLE
Point Annotation Layer Not Loading in BrainSharer

### ISSUE THREAD

**Issue by SanjeevRJ** [ActiveBrainAtlas2/activebrainatlasadmin#207]
The Neuroglancer Data with ID 802 under animal "cFos example" and named "Detected_Cells" isn't displaying anything in BrainSharer when I create a view using it. This annotation layer displays fine when I load it into the Princeton version of Neuroglancer. I've double checked the fields for this layer and was wondering if there was anything on the backend of BrainSharer causing this.

**Comment by eddyod** [comment]
The visible depth range needed to be set to a larger value. It was set at 1um so I set it to 330um. That works, but now the screen flickers on and off when moving the cursor. This is in single user mode also.

**Comment by eddyod** [comment]
Here is part of the error in the developers console:
Uncaught TypeError: undefined has no properties
    e annotations.ts:3459

**Comment by eddyod** [comment]
Ed worked this out with Sanjeev.
