### ISSUE TITLE
Can't Create View with 5 Layers Loaded

### ISSUE THREAD

**Issue by SanjeevRJ** [ActiveBrainAtlas2/activebrainatlasadmin#208]
I'm trying to load fiver layers into a view (shown in the attached image) but after hitting the "Submit" button nothing happens. If I remove any one of the layers, I'm able to successfully create the view. Is there a maximum of 4 layers loaded in a new view?
![image](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/9873598/fffe8e4b-39c3-494a-99a8-5d1fa8f9eb27)

**Comment by eddyod** [comment]
It was concatenating all the titles together and the resulting string was too long. What would you want for the initial title? Just the 1st one? You'll no doubt want to edit it later anyways.

**Comment by SanjeevRJ** [comment]
I actually ended up only needing 4 layers for the view so I can go in and edit it myself. But that's good to know for future reference, thanks!

**Comment by eddyod** [comment]
Well, I should fix this problem so I'll hard code it to the 1st one.
