### ISSUE TITLE
Public brain assessibility "view only" mode

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#209]
Brains marked for public view should be accessible in read only / view only mode as observers.  Effectively it would be possible for a registered user to create a link so others could observe annotation creation.  Yusup has created the Ng code to support this feature but anything multi-user appears to require a registered user account.

I believe Django code can be modified to serve state (without registration) for multi-user (multi=1) and view_only=1.  The co-occurence of the query string variables will no allow observers to push state to others (bidirectional).

**Comment by eddyod** [comment]
Django had nothing to do with it. I modified the Neuroglancer code and it should work. Please test on https://www.brainsharer.org/ng_demo/?id=250&multi=1

The view only is only useful when you are logged in.

**Comment by drinehart1** [comment]
I believe this issue could be resolved by modifying Angular code on front-end:
-if user not logged-in, link to multi-user mode as view_only=1
-if user is logged-in (and is authorized for instructor or collaborator mode - maybe individual from same performance lab as brain), additional functionality is available for multi-user.  Default could be instructor mode unless changed.  This would be first-come, first served.  "owner" opens multi-user link in instructor mode (person can change anything and would have authority to switch observers (others who are actively watching) to collaborators.  We can limit to 2 or 3.

we would need button or key option in Neuroglancer to show all observers (like participants in zoom) with checkboxes/buttons to promote to collaborator.  This would trigger JSON to firebase and back to observer browser -> switch to multi=1

**Comment by eddyod** [comment]
Litao fixed.
