### ISSUE TITLE
Excessive REST calls while volume tool is open

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#210]
When working on a polygon in the volume tool there is a constant call to this url:
GET /brainsharer/landmark_list HTTP/2.0" 200 539

I drew a polygon around the cerebellum. Before I did that, the number of occurrences of landmark list in the logs was 2864.
After I moved off the section the count was: 3198

grep "landmark_list" /var/log/nginx/brainsharer.org_access.log | wc -l

**Comment by drinehart1** [comment]
Is this only single user or also multi? I thought multi synched with fire base and only did callback to brainsharer host when clicking save.Sent from my iPhoneOn Sep 12, 2023, at 20:57, eddyod ***@***.***> wrote:﻿
When working on a polygon in the volume tool there is a constant call to this url:
GET /brainsharer/landmark_list HTTP/2.0" 200 539
I drew a polygon around the cerebellum. Before I did that, the number of occurrences of landmark list in the logs was 2864.
After I moved off the section the count was: 3198
grep "landmark_list" /var/log/nginx/brainsharer.org_access.log | wc -l

**Comment by eddyod** [comment]
I first saw this issue in single user mode. But I just now tested it with multi user mode and it is doing the same thing. The dropdown menus are populated from REST calls to the mysql database. That is what the landmark_list url is doing. It is fetching the different brain regions.
