### ISSUE TITLE
Python brainsharer site-packages 

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#212]
WARNING: Ignoring invalid distribution -ip (/usr/local/share/brainsharer/lib/python3.10/site-packages)
This package was installed incorrectly on brainsharer:
drwxr-xr-x  5 drinehart dklab 4.0K Mar 10  2023 '~ip'
drwxr-xr-x  2 drinehart dklab 4.0K Mar 10  2023 '~ip-23.0.1.dist-info'

What is this?

**Comment by drinehart1** [comment]
Not sure what this is but will add to list for investigation.

Duane

 

From: eddyod ***@***.***> 
Sent: Wednesday, September 13, 2023 11:33
To: ActiveBrainAtlas2/activebrainatlasadmin ***@***.***>
Cc: Duane Rinehart ***@***.***>; Assign ***@***.***>
Subject: [ActiveBrainAtlas2/activebrainatlasadmin] Python brainsharer site-packages (Issue #212)

 

WARNING: Ignoring invalid distribution -ip (/usr/local/share/brainsharer/lib/python3.10/site-packages)
This package was installed incorrectly on brainsharer:
drwxr-xr-x 5 drinehart dklab 4.0K Mar 10 2023 '~ip'
drwxr-xr-x 2 drinehart dklab 4.0K Mar 10 2023 '~ip-23.0.1.dist-info'

What is this?

**Comment by eddyod** [comment]
They are installed incorrectly so just need to be deleted.

**Comment by drinehart1** [comment]
I need to see if that venv is used by other Python code on that server firstSent from my iPhoneOn Sep 13, 2023, at 16:55, eddyod ***@***.***> wrote:﻿
They are installed incorrectly so just need to be deleted.

**Comment by drinehart1** [comment]
I removed packages on brainsharer.org from affected directory.  I'm still not clear how they got there as I don't see where they were imported (unless this was install during testing of something).
