### ISSUE TITLE
Upgrading our brainsharer version of Neuroglancer to match main google project

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#213]
Here is a recursive list of all the files we have modified:
./src/neuroglancer/util/matrix.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/state.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/production.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/user_loader.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/annotation_state_loader.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/user.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/service.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/state_loader.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/demo.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/firebase.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/services/local.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/help/input_event_bindings.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/annotations.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/url_hash_binding.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/default_input_event_bindings.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/clone_polygon.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/volume_session.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/title.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/polygon_options.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/ui/com_session.ts:3:Modified by Brainsharer UCSD/Princeton
./src/neuroglancer/ui/cell_session.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/cell.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/renderlayer.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/annotation_layer_state.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/volume.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/index.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/com.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/annotation/polygon.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/fetch_transformation.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/save_annotation.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/fetch_tracing_annotation.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/invlerp.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/fetch_mouselight_neurons.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/fetch_annotation.ts:15: * Modified for Brainsharer UCSD/Princeton
./src/neuroglancer/widget/histogram.ts:15: * Modified for Brainsharer UCSD/Princeton

**Comment by eddyod** [comment]
Ongoing ...

**Comment by drinehart1** [comment]
Can we close this?

**Comment by eddyod** [comment]
Let's close.
