### ISSUE TITLE
Having to hold "ctrl" key for edit mode is inconvenient

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#217]
Is there a way to activate a sticky key function where edit mode can be entered exclusivley if I press the key combination one time ? I do not want to continuously hold onto the "ctrl" key in order to add, delete, or move points - especially if I am doing multiple edits at the same time. Previously, switching to edit mode allowed me to just move vertices by only using the mouse and also allowed for entire polygon translations.

**Comment by eddyod** [comment]
I was just testing drawing a polygon and holding the control key was the only way I could get it to work.
