### ISSUE TITLE
“type ahead” for brain region/structures when add new landmarks (to avoid typos)

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#22]
"custom" labels (database) -> when adding to new structures, reduce data input errors

**Comment by drinehart1** [comment]
We can modify landmark dropdown to use type ahead code: https://github.com/corejavascript/typeahead.js

pull from db the existing structures and add "New" or "Custom" at end.  This should increase accuracy & usability; and reduce duplicate entries (misspellings)

**Comment by bruce-wayne99** [comment]
This change has been requested by Marissa later. The solution was to use `select2` which is possible in a javascript application but not possible in typescript. Alternative suggested was to open the label dropdown and directly type the label and it takes us to the required label directly. Issue will be re-opened if alternative does not seem to be useful.
