### ISSUE TITLE
loading annotations without prior annotation layer selected

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#222]
If annotation layer is not previously selected, and user tries to load annotation set, retrieval will fail.  Potential workaround:

a) do not display load annotations dialog unless annotation layer is present
b) auto create annotation layer and load annotation set in new layer
c) provide more descriptive error message (cannot load because annotation layer not present; or cannot load into segmentation/image layer)

**Comment by eddyod** [comment]
This has been replaced by search and load in the new version.
