### ISSUE TITLE
DK109 long loading compared to 2 other urls  and scaling is wrong (id 903)

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#225]
<img width="763" alt="image" src="https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/59492402/b14320df-1552-4c3a-9a2e-9c4041c2716d">

**Comment by eddyod** [comment]
Was the Z resolution on this 10um, as compared to the usual 20um?

**Comment by befriedman** [comment]
no- it should be 20 um

________________________________

**Comment by eddyod** [comment]
I'm going to make a new version of DK109 that will hopefully load faster.

**Comment by eddyod** [comment]
I found out why the scale was wrong and I'm fixing it now.

**Comment by befriedman** [comment]
yea! hope that fixes everything else...
________________________________

**Comment by eddyod** [comment]
The scale has been fixed and the normalization looks good for both channels.
https://www.brainsharer.org/ng/?id=903

**Comment by befriedman** [comment]
Can you re-add the animal id (DK109?) so that I don't lose track...

Thanks and agree normalization looks good- actually great!

Best,

Beth
________________________________

**Comment by eddyod** [comment]
Add it where?
It is listed in the portal: https://www.brainsharer.org/brainsharer/admin/neuroglancer/neuroglancerstate/?q=dk109
Do you want it on the public page? In neuroglancer it is listed as 'DK109 plain' 
https://www.brainsharer.org/ng/?id=903

**Comment by befriedman** [comment]
looks good- somehow missed it in one you sent- see id name (DK109) now


________________________________
