### ISSUE TITLE
https://www.brainsharer.org/ng/?id=679 Trigeminal ganglia- polygons complete but annotations of premotor cells not displayed

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#229]
<img width="718" alt="image" src="https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/59492402/dfd90165-751b-405f-a6a4-e7f216d2591b">

This should be the path for the premotor annotations- can these be displayed in yellow

Existing sparse annotations for premotor in 679 should be removed

At one point we had a url showing both but I can no longer find it? There is a case "787" in brainsharer- but mouse number has been removed and it has been renamed "Polygon segmentation of TG"
1. Is this no longer on Neuroglancer- and only in BrainSharer?
2. Removal of mouse numbers is not helpful especially if this case is no longer housed in Neuroglancer

HELP

**Comment by eddyod** [comment]
Both 679 and 787 are in the database. You can also just search by those numbers if you want, or by title or brain name.
679 has title: "DK79 - Complete TG Contours w/ Rendering"
787 has title: "DK78 Polygon segmentation of TG"

**Comment by eddyod** [comment]
Users can now search by ID, title, or brain name.
