### ISSUE TITLE
URL 787 in Brainsharer is not found in neuroglancer

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#230]
<img width="624" alt="image" src="https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/59492402/1fbabd0a-6d67-4378-9827-2caf5df5eab3">

YIKES

**Comment by eddyod** [comment]
Searching by URL ID was never supported. That is why nothing showed up. The name of the URL in question is: "Polygon segmentation of TG" You can search for that or just type the url with that ID in the browser:
https://www.brainsharer.org/ng/?id=787
Search by either animal name or by the URL name next time.

**Comment by befriedman** [comment]
Hi Ed,

I am still confused- can you dig up the animal name for 787?

Thanks

B
________________________________

**Comment by eddyod** [comment]
I renamed it to: "DK78 Polygon segmentation of TG" 
It now has the animal name in it.  So if you do a search for "DK78" it will pop up,
https://www.brainsharer.org/brainsharer/admin/neuroglancer/neuroglancerstate/?q=dk78

**Comment by befriedman** [comment]
thank you!!!
________________________________
