### ISSUE TITLE
annotations stored in json

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#231]
According ref (https://github.com/google/neuroglancer/issues/526), the native json can handle around 10K annotations.  After that there may be instability.  As we craft a better approach to annotation CRUD, we may wish to focus on segregating the Neuroglancer core data from the data.

This would allow better tracking of events as well

**Comment by eddyod** [comment]
That is a good idea. Maybe we can put all the JSON in firestore, or maybe that postgresql JSON database you mentioned. I had to increase the MB of form data to 10MB when a user hits 'Save' in Neuroglancer. And that is just a hack.

**Comment by eddyod** [comment]
Litao and I put the JSON data as one row of data in the annotation session. Data is no longer stored in 3 separate tables.
