### ISSUE TITLE
NG crashes when trying to "hide" polygon annotations using eye icon on sidebar

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#232]
This is the eye icon I am referring to:
![image](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/6f2b2680-3b74-4ecc-ad02-319170d77f93)

After clicking it, NG becomes unresponsive and when I try to refresh the page I get the following pop-up:
![image](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/262a06e6-72cb-4656-abe7-487273fca399)

If I select "Exit page" I get the following:
![image](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/12621062/9a3e5824-f644-4ac0-b976-bc7ed2965a57)

**Comment by eddyod** [comment]
Which URL ID are you looking at, and which layer?

**Comment by mm6654** [comment]
I tried this on multiple links, and they all had the same result.

**Comment by mm6654** [comment]
Also, it is the polygon or annotations layers in the links. Some of them are id = 787, 758, 538

**Comment by eddyod** [comment]
I just tried with ID 787 and 758 on multiple layers and I can't replicate the error. You're going to have to have Duane look over your shoulder when this happens. Maybe looking at the debug console in the browser will tell you something. Is this happening on a Mac with Chrome?

**Comment by mm6654** [comment]
It's happening on a PC computer through Chrome
