### ISSUE TITLE
"phantom" annotations that cannot be delted created with paste button next to annotation buttons

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#236]
1. - 1. There are two paste buttons, and hovering over both gives the same information which is "Paste annotation from the system's clipboard" which makes it hard to distinguish between the two buttons. Top paste button is the following:
![image](https://github.com/user-attachments/assets/772bc8b1-e7fc-4ef4-a2ed-2868670f0e96)

2. The paste function is used when copying and pasting annotations from one section to the next, but only the bottom paste button works for correct polygon propagation. Here I copied polygon created in section z=102, copied child annotation, and pasted using the top paste button to place annotation in section z=103: 
![image](https://github.com/user-attachments/assets/25700e77-ed64-4878-8634-254df0107b18)

3. "Phantom" annotation is created after copying a polygon from one section (z=102) and pasting using top paste button - instead of pasting copied polygon, it pastes a series of line segments on the following section (z=103): 
![image](https://github.com/user-attachments/assets/c3d17773-cadb-45ea-bb90-e63c7b1d6765)

4. After user navigates away from section z=103, the "phantom" annotation disappears from right panel and only the polygon remains visible: 
![image](https://github.com/user-attachments/assets/bc8e4666-0e27-4fa3-aa06-804871b11140)

5. Since the "phantom" annotation disappears from right panel, it cannot be deleted. The "phantom" annotations can still be edited (can shift around page and add vertices), but vertices cannot be deleted. Two additional vertices were created and showed up on right side panel correctly on section z=103: 
![image](https://github.com/user-attachments/assets/66221218-400c-473b-9e4e-60549650a8f1)

7. Deleting the created vertices from right panel does not delete "phantom" annotation from section 103. This is after one vertex has been deleted. There is still one vertex visible on right panel on section z=103: 
![image](https://github.com/user-attachments/assets/e77223fc-e935-4857-a7bb-1debe95219ee)

8. Here is "phantom" annotation after the two new vertices are deleted - nothing on right panel displays an annotation on section z=103: 
![image](https://github.com/user-attachments/assets/785a0bef-c24b-489c-b089-7fd3771fa219)

**Comment by Joeyonng** [comment]
To propagate the polygons within volumes, users should always use the paste button at the bottom. The description text will be changed so that they can be distinguished.

As for the ghost polygon, this should be a bug and we will investigate it to see what's the problem.

**Comment by Joeyonng** [comment]
The ghost polygon bug is solved. This fix is in the next commit.
