### ISSUE TITLE
QA - unit tests, storing & handling annotations

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#24]

**Comment by drinehart1** [comment]
Log files can be added to folder on webdev.dk.ucsd.edu - 
PROPOSED Selenium test:

a) login test user; b) load contour/annotations; c) create/edit new contour; d) save to db; e) verify contours in db match json output from browser

**Comment by bruce-wayne99** [comment]
Usability tests

**Comment by bruce-wayne99** [comment]
There is another issue for tracking usability tests: https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/issues/17
This issue is to track unit tests.

**Comment by bruce-wayne99** [comment]
Unit tests have been added. Closing this issue.
