### ISSUE TITLE
Copy and paste icons

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#241]
Copy annotation text help should be Copy volume or copy polygon

**Comment by eddyod** [comment]
Can we move the child paste icon near the top instead of the bottom. The scroll bar doesn't allow you to go all the way down to the bottom when there are many child annotations.

**Comment by eddyod** [comment]
screen shot of problem.
![screenshot](https://github.com/user-attachments/assets/38adf032-7657-4b3d-97de-e1d05c81266f)

**Comment by eddyod** [comment]
![screenshot](https://github.com/user-attachments/assets/7ff2a59a-7046-4486-81dd-406bf725a190)

**Comment by Joeyonng** [comment]
Can you save this state and give me the state number?

**Comment by eddyod** [comment]
https://brainsharer.org/ng/?id=936

**Comment by Joeyonng** [comment]
This feature has been implemented.
