### ISSUE TITLE
Points table in Admin Portal does not show associated link id or user that created them

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#244]
Beth and I tried checking for the cloud point annotations that she started on DK78, but we could not find them since the user is currently under "edward" instead of "Beth".

Additionally, since the link id is not being displayed it is impossible to know what neuroglancer state the point annotations are linked to. 

<img width="805" alt="Screenshot 2024-08-20 at 3 48 38 PM" src="https://github.com/user-attachments/assets/5c84b2a9-8301-4faa-b160-94106d7abaa8">

**Comment by eddyod** [comment]
I'll put the link in that table above. I'll also put the created data as that will help identify it.
