### ISSUE TITLE
Copied-and-pasted polygons should clone the (x, y) coordinates

### ISSUE THREAD

**Issue by soliao** [ActiveBrainAtlas2/activebrainatlasadmin#251]
In the following example, I copied the polygon on z=53 and pasted it onto z=52.

The planar coordinates of the polygon on z=53 is (18561, 25582), but the cloned polygon on z=52 becomes (19396, 26009).

Because adjacent sections on the final Neuroglancer state are expected to be aligned well, the users may want the cloned polygon with the same (x, y) coordinates as the default.

![image](https://github.com/user-attachments/assets/607827e2-2966-4067-ad31-8ccc7f07a03e)

**Comment by eddyod** [comment]
When the polygon pastes, the user needs to be aware of the copy paste procedure.
1. Use the diagonal arrow in the lower right quadrant, then copy the polygon
2. Change z
3. Paste
