### ISSUE TITLE
Image rendering

### ISSUE THREAD

**Issue by soliao** [ActiveBrainAtlas2/activebrainatlasadmin#253]
Occasionally image rendering appears to stop. Neither by clicking the "Load" button or refreshing the browser can resume rendering. What are the factors that slow down the rendering? Is it possible to create a button that triggers the re-rendering of the current view?

![image](https://github.com/user-attachments/assets/ebfa1c5d-985b-4a3e-9641-8621fdfd7dcc)

**Comment by eddyod** [comment]
The user should use the browser refresh to help speed up downloading. Using the 'Load' button will reload what is in the database and may overwrite any new work or changes the user has made since last saving.
