### ISSUE TITLE
Add more options to side sectioned first dropdown under Histology tab for Admin Portal

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#257]
Currently, under the Histology tab we can only specify whether left/right side was sectioned first. 
![image](https://github.com/user-attachments/assets/6e3daa1b-2781-4863-9e03-baae97e16e85)

Can we add the following options to side sectioned first drop-down?
- if orientation is "sagittal" the options for side sectioned first should be "left" or "right" (this is already done)
- if orientation is "horizontal" the options for side sectioned first should be "dorsal" or "ventral"
- if orientation is "coronal" the options for side sectioned first should be "anterior" or "posterior"

**Comment by drinehart1** [comment]
modify web portal in code but needs testing prior to release

**Comment by eddyod** [comment]
I changed the choices text to use a class. Though the javascript needs work as it is not working. I also put Left = ASC and right = DESC as the sectioning page uses this. That ASC/DESC gets appended to the mysql query. The other fields will have no effect on the sections as it will default to ASC ordering in brain/admin.py line 149:
```
    def section_number(self, obj) -> str:
        animal = obj.slide.scan_run.prep_id
        histology = Histology.objects.get(prep_id=animal)
        orderby = histology.side_sectioned_first

        if orderby == 'DESC':
            sections =  Section.objects.filter(prep_id__exact=animal).filter(channel=1)\
                .order_by('-slide_physical_id', '-scene_number')
        else:
            sections = Section.objects.filter(prep_id__exact=animal).filter(channel=1)\
                .order_by('slide_physical_id', 'scene_number')
```

**Comment by drinehart1** [comment]
The javascript to do the dynamic UI is located in separate file: assets/admin/js/histology.js

This file will only get moved to correct location with python .\manage.py collectstatic
Note: js file is referenced in brain/admin.py ~line 47:
class Media:
        js = ('admin/js/histology.js',)  # relative path in static folder

If this command is run, js is loading without 404 error, I can test again on my end.

**Comment by eddyod** [comment]
Test again. The javascript should be loading. Take note of the code above that produces the sections. Unless you pick 'Right/DESC', it will default to ordering the sections by ASC for the rest of the options.

**Comment by drinehart1** [comment]
This is working for me.  Issue may be closed
