### ISSUE TITLE
ID 945 crashed

### ISSUE THREAD

**Issue by soliao** [ActiveBrainAtlas2/activebrainatlasadmin#260]
Neuroglancer state ID 945 crashes

Issue 1: The "Selection" panel does not show up when I click select any volume/cloud on the "Annotation" panel

![image](https://github.com/user-attachments/assets/3680c670-7ec0-4631-a710-e8ead5abc58f)

Issue 2: Once I click "Load", there will be a duplicate annotation panel. This is a screenshot after I hit "Load" for a couple of times:

![image](https://github.com/user-attachments/assets/b099ddf6-7c59-4d59-b8bf-5586becf515d)

Could you please restore this state and investigate the root cause? Thank you.

**Comment by eddyod** [comment]
Try 948. I made a copy and increased the RAM

**Comment by soliao** [comment]
ID 948 has the same issues. Left click selecting "Load" or Right click selecting any layer will create a new panel on the right. These panels can not be closed.

![image](https://github.com/user-attachments/assets/721f8e5a-4d7d-4d26-8e68-86ad8bf5c2a1)

**Comment by eddyod** [comment]
Don't bother using the 'Load' icon. You need to do a hard refresh to get the new code and remove the old code from your browser cache. Do a google search on hard reload/refresh for the correct keys for your browser.

**Comment by soliao** [comment]
Hard refresh solved this issue for ID 945. Closing the issue.
