### ISSUE TITLE
Display Neuroglancer ID on the "Layer points/polygons" page

### ISSUE THREAD

**Issue by soliao** [ActiveBrainAtlas2/activebrainatlasadmin#261]
Currently the table displayed on the **Brainsharer --> NEUROGLANCER --> Layer points/polygons** page contains the following columns:

- ANIMAL
- OPEN NEUROGLANCER
- USER
- SHOW POINTS LINKS
- UPDATED
- CREATED

Suggestion: Add the column called "ID" (the Neuroglancer ID) as the first column to the table.

Reason: Showing IDs on the table can help users confirm the source of points/polygons they want to export.

![image](https://github.com/user-attachments/assets/a44422ae-27d7-4f0d-b834-b51118edb7e4)

**Comment by eddyod** [comment]
I added that as the first column. Close this issue when it has been verified,

https://www.brainsharer.org/brainsharer/admin/neuroglancer/points/

**Comment by soliao** [comment]
The ID column is added.
