### ISSUE TITLE
Preserving the order of points exported from a polygon

### ISSUE THREAD

**Issue by soliao** [ActiveBrainAtlas2/activebrainatlasadmin#262]
The order of points in the same polygon exported to the page "Layer points/polygons" are sorted by their X coordinates. However, to reconstruct the polygon using external software, the order of points should follow from one vertex to the next vertex via the edges.

For example, for ID 945 (z=72), the points in the volume "SC_Gray_Matter_Ventral_Left" have the following order:

![image](https://github.com/user-attachments/assets/2dacf985-5639-47f4-94c5-a33fe8aa04b7)

But in the exported data table, the points are sorted by the X coordinates instead:

![image](https://github.com/user-attachments/assets/fcb35a0f-261f-4452-8e5f-6bef687f561a)

**Suggestion**: The exported points on the page "Layer points/polygons" should keep the order from the original polygon's child annotations to preserve the information of the graph.

**Comment by eddyod** [comment]
OK, I'll work on this.

**Comment by eddyod** [comment]
I added a column named 'Order' that will have the ordering for volumes/polygons. The column is just 0 for cloud points.
The ordering starts at 0. 
https://www.brainsharer.org/brainsharer/admin/neuroglancer/points/points-data/948

**Comment by soliao** [comment]
*2024-10-02 Updates*

Some polygons have the correct "Order" information. However, for some polygons, the order of their child annotations are all set to be "999". Could you please investigate this situation? Thank you.

This is an example of a polygon whose point orders are all 999:
![image](https://github.com/user-attachments/assets/cbcec36d-4f74-40be-82fa-b117848e0c13)

**Comment by eddyod** [comment]
This has been implemented, please test.
https://www.brainsharer.org/brainsharer/admin/neuroglancer/points/points-data/948

**Comment by soliao** [comment]
Tested and closed this issue.
