### ISSUE TITLE
Volume-level UUIDs for exported points/polygons table

### ISSUE THREAD

**Issue by soliao** [ActiveBrainAtlas2/activebrainatlasadmin#263]
Currently, the table on the "Layer points/polygons" page has a column called **UUID**. For volume objects, each section has a unique UUID, i.e., the UUID is at the section-level.

For example, the table below shows that for this single volume "SC_Gray_Matter_Ventral_Left", polygons on z=53 and z=78 has different UUIDs.
![image](https://github.com/user-attachments/assets/695dba7d-bb63-448d-8c84-428bf48f7e1b)

**Suggestion**: The UUID should be at the volume-level. For each volume on the Neuroglancer annotation panel, the same UUID should be assigned to all polygons that belong to that volume.

For example, ID 945 has 2 clouds and 6 volumes (see below). In the exported table, only 8 (2+6) unique UUIDs are needed. In this case, the UUID column will be used for distinguishing the two volumes that both are labeled as "SC_Gray_Matter_Ventral_Right", as well as the two volumes labeled as "SC_Gray_Matter".

![image](https://github.com/user-attachments/assets/e2dd392e-5bd5-49c6-820f-c3a9bbe73e52)

**Comment by eddyod** [comment]
This has been implemented, please test.

**Comment by soliao** [comment]
Tested and closed this issue.
