### ISSUE TITLE
Selecting orientation under "Histology" tab causes error and will not save

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#267]
Under the Histology tab, I tried adding DK184 sectioned in the sagittal orientation starting from the left side, but after selecting both orientation and side sectioned first and hitting save the page showed the selection was not valid.
![image](https://github.com/user-attachments/assets/076d2a06-baab-441d-9886-35bf966a7049)

I tried selecting coronal as a different orientation and when I try to save the changes the page crashes:
![image](https://github.com/user-attachments/assets/55a2febc-5acb-4d6e-8c7c-09d9335320c5)

**Comment by eddyod** [comment]
Fixed.
