### ISSUE TITLE
Bug: log in option not visible in webdev.dk.ucsd.edu/preview

### ISSUE THREAD

**Issue by bruce-wayne99** [ActiveBrainAtlas2/activebrainatlasadmin#32]
Steps to reproduce
- Go to webdev.dk.ucsd.edu
- Click access preview
- If a user is not logged in, no log in option is not present in the top right corner.
- Screenshot error in console:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/25129274/160495194-b8101bc4-92ea-4bda-af84-71937887eb02.png">

**Comment by eddyod** [comment]
This should be fixed. go a git pull, rebuild and redeploy and test
