### ISSUE TITLE
Browser selective functions

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#36]
I cannot use annotation tool to mark COMs when the Neuroglancer state i(DK61) is opened in Firefox
The annotation tool does work on to mark COMs when the same state (DK61) is opened in Chrome

I was testing opening on the 2 browsers to see if the upload speed differed between firefox and chrome

Thanks

Beth

**Comment by bruce-wayne99** [comment]
Hello Beth,
thanks for reporting this here. I'll look into it, also is this happening on Ratto ?

**Comment by befriedman** [comment]
Hello,

No this happened on my laptop - macbook air.

Thank you,

Beth
________________________________
