### ISSUE TITLE
Neuroglancer resolutaion updating

### ISSUE THREAD

**Issue by madwilliam** [ActiveBrainAtlas2/activebrainatlasadmin#37]
Currently neuroglancer do not update the resolution if the following operations are performed:
1. open an image with resolution A
2. close the image layer
3. open a new image layer with resolution B

In that situation the resolution for the neuroglancer state would be resolution A while it should be B.

We need to investigate if in that situation any annotation the user made in that state would be saved in the database with resolution A or B as conversion between pixel and microns.

We have some evidence to believe that it would be saved in resolution B but we do not know why

**Comment by bruce-wayne99** [comment]
Updates from meeting
- If there is a single image in the neuroglancer, reset the resolution of neuroglancer to the resolution of the image.
- Django changes to consider using the resolution from the neuroglancer state.
- Changes to transformation API: send resolution as a parameter. [William working on changing the API]

**Comment by bruce-wayne99** [comment]
Issue has been fixed. Resolution of neuroglancer gets automatically updated when a new image is opened and the old image in the layer is closed.
