### ISSUE TITLE
Sign up for Brain Sharer

### ISSUE THREAD

**Issue by david-kleinfeld** [ActiveBrainAtlas2/activebrainatlasadmin#40]
This does not work - please fix it asap

Thank you - David

**Comment by eddyod** [comment]
I disabled the submit buttons and put up a warning notice:
This page is under construction and all functionality has been disabled. We are expecting all site functionality to be available in the summer of 2022.

You can contact us by sending a request via email to Duane Rinehart: drinehart at ucsd.edu

**Comment by eddyod** [comment]
This should have been closed long ago. Users can login with Google, Github or a local login.
