### ISSUE TITLE
add separate button for saving neuroglancer state and annotataions

### ISSUE THREAD

**Issue by madwilliam** [ActiveBrainAtlas2/activebrainatlasadmin#46]

**Comment by bruce-wayne99** [comment]
- API will take the neuroglancer state and the current annotation layer as input, API to be developed by @madwilliam

**Comment by bruce-wayne99** [comment]
- Live version at webdev.
- Go to webdev.ucsd.edu, click on access preview.
- Open a new annotation tab, draw some annotations click on save annotations in the sidebar.
