### ISSUE TITLE
auto assign the right resolution when importing annotations

### ISSUE THREAD

**Issue by madwilliam** [ActiveBrainAtlas2/activebrainatlasadmin#48]
When importing annotations in a annotation layer, neuroglancer should get the scan resolution of the corresponding animal and apply it to the source dimensions.

**Comment by bruce-wayne99** [comment]
I think we may need a column in annotations table for storing the resolution at which the annotation was drawn. @madwilliam @eddyod @drinehart1 thoughts ?

**Comment by drinehart1** [comment]
It is my understanding that information is an attribute of the brain imaging (manually entered now but should be included in czi file).  We store the information at present so I prefer not to double-store it.  If you’re not able to reference it directly, we could add to REST response.  Would that work?

Duane

**Comment by bruce-wayne99** [comment]
Issue has been fixed. Now annotations resolution in automatically loaded with the annotations.
