### ISSUE TITLE
Need a function to change colors of multiple annotation units

### ISSUE THREAD

**Issue by KuiQian** [ActiveBrainAtlas2/activebrainatlasadmin#50]
Currenly changing colors of existing annotation points has to be done one by one.

It would be better if there would be a function to change colors or other features of multiple annotation points.

**Comment by bruce-wayne99** [comment]
@KuiQian can we meet on Wednesday and discuss about this ?

**Comment by KuiQian** [comment]
Sure, see you then.

**Comment by bruce-wayne99** [comment]
Discussion with Kui:
Currently if a user selects a color in the color picker button and imports the annotations, the annotations are not imported with that color. 
Expected behavior: If the color component of the annotations is not present load them with the color in the color picker.

**Comment by bruce-wayne99** [comment]
@KuiQian I have fixed this bug.
You can try it out at webdev.dk.ucsd.edu
Let me know if the bug still exists otherwise I'll close the issue.
