### ISSUE TITLE
mouse/pointer color when on top of sagittal view

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#52]
when moving mouse over image, mouse blends into background (or disappears).  Either way, it is not visible if image is very light (MD585).  This may be adjusted using the "Rendering" tab on image layer but it is not intuitive.  Some option for automating color swap or adjusting pointer would be very useful.

**Comment by bruce-wayne99** [comment]
Issue has been addressed in Google's neuroglancer, recent merge implemented the feature.
