### ISSUE TITLE
Neuro : volume session edit mode

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#56]
If volume (category) is not selected in top part of annotation panel, on volume session modal menu, 'edit selected volume' should not be displayed or disabled (showed in light grey and not clickable)

This is preferred rather than getting user's hopes up he/she is going to edit something and then getting message:
'Please select pin and volume in current layer to start editing'

In essence, the volume session menu should be contextual

**Comment by bruce-wayne99** [comment]
I think having the instruction will help user in using the volume session tool. If we don't show the error message and the user sees the Edit button disabled user might be confused about how the button works and may think it is some kind of bug.
