### ISSUE TITLE
Features and bug fixes for the volume tool

### ISSUE THREAD

**Issue by madwilliam** [ActiveBrainAtlas2/activebrainatlasadmin#61]
Hey Naga, 

    After using the tool for a while with Duane we discovered a few more places where we can improve the tool:
    
        1.  Sorting the polygons by sections in the volume annotations
     
        2.  There is a bug right now where the description of the structure name appears on the first few polygons as well as the volume annotation.  We should fix it to display only on the volume annotation
        
        3. It would help direct the user's attention if the volume annotation itself does not display the coordinates of the source point
        
        4. Control right click on a polygon should expand the list of polygons of a volume if it is not expanded as well as select the corresponding polygon.
        
        5. It would be nice if the volume tool enters edit mode if a contour is present on a section, and enters draw mode if no contours is present on the current section.

Knocking out bugs is what makes the difference between a software that is difficult to use and one that just works.  Keep up the good work!

**Comment by bruce-wayne99** [comment]
Thanks for the list @madwilliam @drinehart1 I'll start working on these.

**Comment by bruce-wayne99** [comment]
the 5th point `    5. It would be nice if the volume tool enters edit mode if a contour is present on a section, and enters draw mode if no contours is present on the current section.
` I remember Prof. Yoav bringing up this point but Beth said that she likes the current functionality (draw/edit/view mode).

**Comment by drinehart1** [comment]
Separate issue for point5

**Comment by drinehart1** [comment]
- Restrict depth scale to below depth resolution micro meter by default.

**Comment by bruce-wayne99** [comment]
> * Restrict depth scale to below depth resolution micro meter by default.

Restricted to half the 'z' scale resolution. The rest of the issues have been resolved.

Closing this issue.
