### ISSUE TITLE
    5. It would be nice if the volume tool enters edit mode if a contour is present on a section, and enters draw mode if no contours is present on the current section.

### ISSUE THREAD

**Issue by drinehart1** [ActiveBrainAtlas2/activebrainatlasadmin#62]
5. It would be nice if the volume tool enters edit mode if a contour is present on a section, and enters draw mode if no contours is present on the current section.

**Comment by drinehart1** [comment]
Need more info

**Comment by bruce-wayne99** [comment]
Not relevant. Current functionality is accepted.
