### ISSUE TITLE
add ability to show 3d density plot in neuroglancer

### ISSUE THREAD

**Issue by madwilliam** [ActiveBrainAtlas2/activebrainatlasadmin#70]
https://www.google.com/url?sa=i&url=https%3A%2F%2Ftex.stackexchange.com%2Fquestions%2F142768%2Fcreate-3d-heatmap-density-plot-using-tikz&psig=AOvVaw2FBIhgNBKDyanDWdoso-Ze&ust=1653497483765000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPCJmaPM-PcCFQAAAAAdAAAAABAb

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.researchgate.net%2Ffigure%2FMultivariate-kernel-density-estimation-kde-for-the-bootstrap-distributions-of-nodal_fig4_301761244&psig=AOvVaw2FBIhgNBKDyanDWdoso-Ze&ust=1653497483765000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPCJmaPM-PcCFQAAAAAdAAAAABAm

**Comment by bruce-wayne99** [comment]
Closing this issue for now. Will re-open later if feature is useful/needed.
