### ISSUE TITLE
Expand Dynamic Range

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#78]
Some brains need more contrast to see distinguishing features, but dynamic range is limited to about 65,500. Typing in the number does not change contrast - it goes back to 65,535. Would it be possible to increase the range to 100,000?

![image](https://user-images.githubusercontent.com/12621062/171720911-f24309f0-5dc4-4efc-8616-5bbd7bc1b4a1.png)

**Comment by bruce-wayne99** [comment]
Based on my investigation, the range information is loaded from the image data and it can't be altered, even if we increase the range all the pixels will be in 0-65500 range itself and it won't help in improving the contrast. We can try using the "gamma" scrollbar feature and see if we can adjust it and improve contrast

**Comment by bruce-wayne99** [comment]
I was able to add controls to adjust contrast and brightness. Reference: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/sliceview/image_layer_rendering.md

**Comment by eddyod** [comment]
Naga, you're right. The images are 16bit, and so have a range from 0-2**16 -1.
