### ISSUE TITLE
Vertex cannot be deleted

### ISSUE THREAD

**Issue by mm6654** [ActiveBrainAtlas2/activebrainatlasadmin#79]
For DK55: 

After propagating the polygon from slide 157 to slide 158 and editing the vertices, one of the vertices moves, but leaves a copy of the same vertex on its original position. I tried deleting the extra vertex, but it would not delete. Extra vertex is still attached to the original vertex. 
![image](https://user-images.githubusercontent.com/12621062/171761484-6761c65a-bbda-4b23-b222-b8a4ab5b47c9.png)

After deleting the original vertex - it detaches from the polygon but leaves another copy behind and remains attached to the first copy of the vertex (see picture below).
![image](https://user-images.githubusercontent.com/12621062/171761647-ce9fbe3e-3619-48d2-a385-531fb8e7f333.png)

The two connected vertices can be moved, but not deleted as shown in the image below.
![image](https://user-images.githubusercontent.com/12621062/171761743-7558c1d4-978d-4b1f-8094-7117ac348959.png)

**Comment by bruce-wayne99** [comment]
Thanks Marissa @mm6654  for raising this bug with screenshots. I'll look into this.

**Comment by bruce-wayne99** [comment]
This bug appears when user creates two vertices at the same location (usually happens when the user makes a double click instead of a single click while creating a vertex). I have put some restrictions to allow unique positions for each vertex.
Closing this issue.
