### ISSUE TITLE
Abakit missing module

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#91]
Abakit is missing the file below. 
 File "/usr/local/share/activebrainatlas/lib/python3.8/site-packages/abakit/atlas/NgSegmentMaker.py", line 13, in <module>
    from abakit.lib.utilities_cvat_neuroglancer import NumpyToNeuroglancer
ModuleNotFoundError: No module named 'abakit.lib.utilities_cvat_neuroglancer'

**Comment by drinehart1** [comment]
I believe this file has been moved to preprocessing-pipeline/src/lib/utilities_cvat_neuroglancer.py

I'd like to keep it there for now as I'm looking at how best to deal with chunk size calcs
