### ISSUE TITLE
Abakit setup

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#92]
I had to replace the lines below in abakit/setup.py

#setuptools.setup(name = 'abakit',packages = ['abakit'], package_dir = {'abakit':'src'})
setuptools.setup()

While in the virtualenv, the first line does not work with:
python -m build

**Comment by drinehart1** [comment]
William and I have experienced multiple issues with recompiling the abakit (mainly it not copying files into venv properly).  Temp workaround is to copy the files manually however I think it may be easier to simply reintegrate non-shared components back into preprocessing-pipeline

**Comment by drinehart1** [comment]
Since we have phased out abakit, I think we can close this bug
