### ISSUE TITLE
Error in preprocessing pipeline

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#95]
I put 3 czi files from DK59 on my computer and ran:
python src/create_pipeline.py --animal DK59 and got this error:

  File "preprocessing-pipeline/src/lib/TiffExtractor.py", line 113, in create_web_friendly_image
    scene_index.append(section.scene_number-1)
AttributeError: 'result' object has no attribute 'scene_number'

Am I doing something wrong. Can we update the documentation if I am running the wrong script.

**Comment by drinehart1** [comment]
I was working on that code today but am not finished.  Most recent code is on ratto.  I should be done by tomorrow.

Duane

 

From: eddyod ***@***.***> 
Sent: Monday, July 11, 2022 18:53
To: ActiveBrainAtlas2/activebrainatlasadmin ***@***.***>
Cc: Duane Rinehart ***@***.***>; Assign ***@***.***>
Subject: [ActiveBrainAtlas2/activebrainatlasadmin] Error in preprocessing pipeline (Issue #95)

 

I put 3 czi files from DK59 on my computer and ran:
python src/create_pipeline.py --animal DK59 and got this error:

File "preprocessing-pipeline/src/lib/TiffExtractor.py", line 113, in create_web_friendly_image
scene_index.append(section.scene_number-1)
AttributeError: 'result' object has no attribute 'scene_number'

Am I doing something wrong. Can we update the documentation if I am running the wrong script.

**Comment by drinehart1** [comment]
I just did commit to repository.  The scene number issue results from difference in czi files starting numbering at 0 but DB starts numbering at 1.  Code modified.  If resolved, this bug can be closed
