### ISSUE TITLE
Fix gitignore in preprocessing pipeline

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas2/activebrainatlasadmin#97]
Can we put add pyc files to the .gitignore in the base of the preprocessing pipeline. They shouldn't be in the project.

You'll have to clear the cache:
https://stackoverflow.com/questions/19663093/apply-gitignore-on-an-existing-repository-already-tracking-large-number-of-file

**Comment by drinehart1** [comment]
I see the filter in .gitignore.  When you revised preprocessing-pipeline, did you do a cache clear, Ed?  If so, we can close this bug
